CruGlobal/idm-user-management

- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
This attribute is redundant and caused entries to have multiple CN's when creating a new deactivated user.
> CN should be set through the DN only

- api/pom.xml
- inspektr/pom.xml
- ldaptive/pom.xml
- migration/pom.xml
- pom.xml
@frett 
I want to make sure my migration project uses a different version of idm-user-management than my non migration projects.
> Create migration specific artifact version number.

- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
Because Relay users are members of role groups not allowed by the `GroupValueTranscoder` which is configured with group base dn (ou=relay,ou=group,dc=ccci,dc=org), exceptions with stack trace are being logged as below, which muddy up the log unnecessarily. So, don't log the full exception stack trace, as this is info level logging and enough info is logged without it. 
AbstractUserLdapEntryMapper.getGroupValues(376) - Caught exception resolving group from group dn cn=readers,ou=system,ou=role,dc=ccci,dc=org
java.lang.IllegalArgumentException: cn=readers,ou=system,ou=role,dc=ccci,dc=org
<full stack trace>
Another option I suppose is to make the group base dn shorter (i.e. dc=ccci,dc=org). However, this seems non intuitive and also the app in question has no interest in groups other than …
> Don't log the full exception stack trace

- api/src/main/java/org/ccci/idm/user/User.java
- api/src/test/java/org/ccci/idm/user/UserTest.java
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
addresses a corner case of reseting an email address to itself would make it unverified.
> Preserve emailVerified flag when we aren't actually changing the email

- api/pom.xml
- api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
- api/src/test/java/org/ccci/idm/user/AbstractDefaultUserManagerIT.java
This interface can be used to tie external functionality into the UserManager.
Such as: Global Registry sync, Password Policy enforcement, or Password history
tracking. More methods will be added as needed over time.
> create a UserManagerListener interface

- api/pom.xml
- api/src/main/java/org/ccci/idm/user/User.java
- api/src/main/java/org/ccci/idm/user/util/HashUtility.java
- ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoIT.java
@frett In order to support legacy Relay security answer hashes.
> Replace bcrypt with jasypt strong password encryption

- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java
This will be used to implement an advance search for admin tools. This is not being exposed at the interface or UserManager level because it is currently very specific to Ldaptive.
> relax visibility on findAllByFilter

- api/pom.xml
- api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
- inspektr/pom.xml
- inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UserAuditResourceResolver.java
- pom.xml
The package for inspektr was changed from com.github.inspektr to org.jasig.inspektr
> upgrade to inspektr 1.2.GA for CAS 4.1

- api/src/main/java/org/ccci/idm/user/User.java
- api/src/main/java/org/ccci/idm/user/dao/ldap/AbstractLdapUserDao.java
- api/src/main/java/org/ccci/idm/user/dao/ldap/Constants.java
- api/src/test/java/org/ccci/idm/user/UserTest.java
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
- Make preferredName part of the core name attribute set
- internally only track preferredNames that are different from firstName
- in eDirectory store fully resolved preferredName
> Preferred name

- api/pom.xml
- inspektr-legacy/pom.xml
- inspektr-legacy/src/main/java/org/ccci/idm/user/inspektr/resolver/ReturnUserAuditResourceResolver.java
- inspektr-legacy/src/main/java/org/ccci/idm/user/inspektr/spi/UpdateUserAuditResourceResolver.java
- inspektr-legacy/src/main/java/org/ccci/idm/user/inspektr/spi/UserAuditResourceResolver.java
- inspektr-legacy/src/main/java/org/ccci/idm/user/inspektr/spi/UserGroupAuditResourceResolver.java
- inspektr-legacy/src/main/java/org/ccci/idm/user/inspektr/util/InspektrSerializationUtils.java
- inspektr/pom.xml
- inspektr/src/main/java/org/ccci/idm/user/inspektr/resolver/ReturnUserAuditResourceResolver.java
- inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UserAuditResourceResolver.java
- ldaptive/pom.xml
- pom.xml
This PR updates the inspektr dependency for CAS 5.1.2. I'm also providing a forked legacy module to allow more gradual upgrades if needed.
Once everything is upgraded I will drop the legacy module
> Inspektr upgrade

- api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java
Google guava 23 updated the `FluentIterable.of()` signature to require either no items, or a single item followed by varargs.
Neither of these signatures support an array, so we just wrap the array in a list ourselves.
This method was marked `@Beta`, so it was use at our own risk. I would replace usages with a `Stream`, but we are still maintaining Java 6 compatibility
> update FluentIterable usage to address signature change to `@Beta` method

- api/src/main/java/org/ccci/idm/user/User.java
- api/src/main/java/org/ccci/idm/user/dao/ldap/AbstractLdapUserDao.java
- api/src/main/java/org/ccci/idm/user/dao/ldap/Constants.java
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
This adds the Master person id to the User model (ldap attributes are already created for production).
I'll be creating a v0.4.4 maintenance release since master is currently backwards incompatible with CAS 4.1.
> support tracking the master person id for a user

- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
the `LdapAttributes` created here will `REPLACE` the same attribute already in LDAP. 
When there is a null value, creating an attribute with a name no value will end up being handled as removing the attribute from the LDAP server.
> don't attempt to store null ReadableInstants

- api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
- api/src/main/java/org/ccci/idm/user/User.java
- api/src/main/java/org/ccci/idm/user/UserManager.java
- api/src/main/java/org/ccci/idm/user/dao/AbstractUserDao.java
- api/src/main/java/org/ccci/idm/user/dao/UserDao.java
- api/src/main/java/org/ccci/idm/user/dao/ldap/Constants.java
- api/src/test/java/org/ccci/idm/user/DefaultUserManagerMfaTest.java
- api/src/test/java/org/ccci/idm/user/TestUtil.java
- inspektr/src/main/java/org/ccci/idm/user/inspektr/util/InspektrSerializationUtils.java
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
- ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoIT.java
We aren't tracking the `ccciGuid` within Okta, this can potentially complicate the Okta to eDir sync. So, we are deprecating and making sure we are no longer dependent on the `ccciGuid`
> Deprecate ccci guid

- api/pom.xml
- api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
- api/src/main/java/org/ccci/idm/user/User.java
- api/src/main/java/org/ccci/idm/user/UserManager.java
- api/src/main/java/org/ccci/idm/user/dao/AbstractUserDao.java
- api/src/main/java/org/ccci/idm/user/dao/UserDao.java
- api/src/main/java/org/ccci/idm/user/dao/ldap/AbstractLdapUserDao.java
- api/src/main/java/org/ccci/idm/user/exception/GroupException.kt
- api/src/main/java/org/ccci/idm/user/exception/GroupNotFoundException.kt
- api/src/main/java/org/ccci/idm/user/exception/UserException.java
- api/src/main/java/org/ccci/idm/user/query/Attribute.java
- api/src/main/java/org/ccci/idm/user/query/ComparisonExpression.java
- ldaptive/pom.xml
- ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java
- ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoIT.java
- ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoTest.java
- okta/pom.xml
- okta/src/main/java/org/ccci/idm/user/okta/OktaGroup.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/FallbackDaoOktaUserDaoListener.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/listeners/FallbackDaoOktaUserDaoListener.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/listeners/OktaPasswordHackForCreateUserListener.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/util/ClientUtils.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/util/UserUtils.kt
- pom.xml
Create an OktaUserDao supporting the following functions:
- Lookup users
- Create/Update users
- Search for users
- List Groups
- Manage Group membership
Things to do in a followup PRs:
- Support Reactivate/Deactivate users
- Potentially optimize API calls to reduce API request load (not sure how this will currently measure up against Okta limits, plus utilizing the built-in SDK caching mechanism should help)
> OktaUserDao

- okta/src/main/java/org/ccci/idm/user/okta/dao/listeners/FallbackDaoOktaUserDaoListener.kt
This works around several issues with creating users in The Key. 
- it avoids Okta creating the user in LDAP with a temporary password. Instead Okta will associate the existing LDAP user with the Okta user.
- it allows us to track additional key operational attributes within LDAP when creating the user's account. (self service related keys)
To use this all the OktaLDAPAgents and services using the `FallbackDao` need to use the same LDAP server. For the stage/preview environment I'm using `tledira02.cru.org` which is located at AWS. For production I will use `pledira03.aws.cru.org`
> create users in the fallback DAO as well as Okta

- api/src/main/java/org/ccci/idm/user/query/BooleanExpression.java
- api/src/main/java/org/ccci/idm/user/query/ComparisonExpression.java
- api/src/main/java/org/ccci/idm/user/query/Expression.java
- api/src/main/java/org/ccci/idm/user/query/NotExpression.java
- ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoExpressionConversionTest.java
- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
when an account is deactivated for The Key in Okta we perform the following actions:
1. suspend the account
2. set the `original_email` to the user's email address
3. update the user's email address to be a unique placeholder. This will free up the email address to be used by another account.
The intention of deactivation in The Key is to remove an account in a reversible manner and not let the deactivated account interfere with a user wanting to reuse the email address.
> OktaUserDao activate deactivate support

- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
When a user creates a new Okta account they are in a `PROVISIONED` state until the user activates the account by clicking a link in their email. Accounts in this state can not be suspended.
Because the account can't be suspended, just renaming the account to our deactivated account pattern still allows the user to interact with the account if they can determine the deactivated email address or more easily if they just click the `Activate Account` link that was originally emailed to them.
To make sure the account is unusable we trigger Okta deactivation (which is a destructive action and prevents any future updates to the account), but I feel this is acceptable because the account was never actively used anywhere, so there shouldn't be any need to restore it.
If we encounter an account …
> Okta deactivate fixes

- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
a `STAGED` account is an account created by an admin for a user without a password that hasn't been activated yet
a `PROVISIONED` account is an account created by a user that hasn't been activated yet.
both are accounts that haven't been used yet
> staged accounts should be handled the same way as provisioned accounts

- okta/src/main/java/org/ccci/idm/user/okta/dao/listeners/FallbackDaoOktaUserDaoListener.kt
- pom.xml
This attribute is, I believe, the only HR attribute that pshr-listener needs to have stored in IDM.
> Restore employee status attribute

- okta/src/main/java/org/ccci/idm/user/okta/OktaGroup.kt
- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
We need to be able to restrict down the groups we get back from the Okta API and also make sure they are the groups we actually care about.
> Okta group adjustments

- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
email search should be case insensitive.
the `searchUsers` extension function utilizes the [Okta List Users API](https://developer.okta.com/docs/reference/api/users/#list-users) in a different manner that doesn't appear to be case sensitive
> filter on the Okta List Users API is case sensitive

- okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
- okta/src/test/java/org/ccci/idm/user/okta/dao/BaseOktaUserDaoTest.kt
- okta/src/test/java/org/ccci/idm/user/okta/dao/OktaUserDaoSaveIT.kt
- okta/src/test/java/org/ccci/idm/user/okta/dao/OktaUserDaoSaveTest.kt
- okta/src/test/java/org/ccci/idm/user/okta/dao/OktaUserDaoUpdateUserTest.kt
This will expose more usable exceptions when there is an error creating a new user.
> Process Okta exceptions when creating a new user
