api/src/main/java/org/ccci/idm/user/DefaultUserManager.java

Disable email validation (migration only).

---

api/src/main/java/org/ccci/idm/user/dao/ldap/Constants.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java

Remove obsolete cruPerson object class dependency.

---

ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java

fix the NPE in modifyDn

---

api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
api/src/main/java/org/ccci/idm/user/UserManager.java
api/src/main/java/org/ccci/idm/user/dao/UserDao.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/io/GroupValueTranscoder.java
ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoIT.java
ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/io/GroupValueTranscoderTest.java
ldaptive/src/test/resources/org/ccci/idm/user/ldaptive/dao/dao-default.xml

I needed the functionality to list out all the members in a specific Group. In the process I also cleaned up a few corner case bugs with group parsing.

implement findAllByGroup

---

api/src/test/java/org/ccci/idm/user/TestUtil.java
ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoIT.java

@hlbraddock 
no library functional changes, just changes to the tests to make them more explicit in testing user object equality.

Test cleanup

---

api/src/test/java/org/ccci/idm/user/UserTest.java

Add missing randomEmail() method.

---

api/src/main/java/org/ccci/idm/user/Group.java
inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UpdateUserAuditResourceResolver.java
inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UserAuditResourceResolver.java
inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UserGroupAuditResourceResolver.java

Audit updates

---

api/src/main/java/org/ccci/idm/user/User.java
api/src/main/java/org/ccci/idm/user/dao/ldap/AbstractLdapUserDao.java
api/src/main/java/org/ccci/idm/user/dao/ldap/Constants.java
api/src/main/java/org/ccci/idm/user/util/HashUtility.java
api/src/test/java/org/ccci/idm/user/UserSecurityAnswerTest.java
api/src/test/java/org/ccci/idm/user/UserTest.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
ldaptive/src/test/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDaoIT.java

Add support for security question and answer.

---

api/src/main/java/org/ccci/idm/user/DefaultUserManager.java

Correctly update Password History

---

api/src/main/java/org/ccci/idm/user/util/HashUtility.java
api/src/test/java/org/ccci/idm/user/util/HashUtilityTest.java

gracefully fail when testing against an invalid hash

---

api/src/main/java/org/ccci/idm/user/DefaultUserManager.java

only validateEmail when we are updating the email

---

api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
api/src/test/java/org/ccci/idm/user/AbstractDefaultUserManagerIT.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java

test EmailAlreadyExistsException

---

api/src/test/java/org/ccci/idm/user/AbstractDefaultUserManagerIT.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java

Actually respect the lack of Attr.EMAIL in an update

Email Attr

---

ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java

This is similar to what we currently do for relayGuids

always set actual key guid on underlying accounts

---

api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
api/src/main/java/org/ccci/idm/user/UserManager.java
api/src/main/java/org/ccci/idm/user/dao/UserDao.java
api/src/main/java/org/ccci/idm/user/dao/ldap/Constants.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/util/GroupUtils.java

This PR provides an API for getting all groups.
The API is made available as part of the various user based class/interface infrastructure, and while not particular to a user, is nonetheless made available here until a more suitable framework becomes available for providing group DAO.

Add support to get all groups

---

inspektr/src/main/java/org/ccci/idm/user/inspektr/resolver/ReturnUserAuditResourceResolver.java
inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UserAuditResourceResolver.java
inspektr/src/main/java/org/ccci/idm/user/inspektr/spi/UserGroupAuditResourceResolver.java
inspektr/src/main/java/org/ccci/idm/user/inspektr/util/InspektrSerializationUtils.java

This is fairly low priority.
- adjust the format of Groups in inspektr audit logs
- import the audit resolver we added to The Key for the new API endpoints. This is a better location for it, but didn't want adding it here to delay getting that code out to production.

Inspektr tweaks

---

.travis.yml
ldaptive/pom.xml
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/io/ReadableInstantValueTranscoder.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/mapper/AbstractUserLdapEntryMapper.java
ldaptive/src/test/resources/org/ccci/idm/user/ldaptive/dao/ldap.xml
pom.xml

Requires Java 8 or better client applications to idm-user-management.

Ldaptive 1.2.1 upgrade

---

api/pom.xml
api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
api/src/main/java/org/ccci/idm/user/util/UserUtil.java
api/src/test/java/org/ccci/idm/user/util/UserUtilTest.java
pom.xml

I need this utility function within The Key to determine if a value is a user's guid. I figured it was better to put it here than in The Key specifically.

Simple util function to validate GUIDs

---

api/src/main/java/org/ccci/idm/user/DefaultUserManager.java
api/src/main/java/org/ccci/idm/user/dao/UserDao.java
ldaptive/src/main/java/org/ccci/idm/user/ldaptive/dao/LdaptiveUserDao.java

This will make it easier to implement parts of the `OktaUserDao`

Refactor some dao methods

---

okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt

Existing deactivated accounts got migrated over to Okta on production, this updates the deactived read logic to recognize the legacy deactivated accounts

Recognize legacy deactivated accounts

---

api/src/main/java/org/ccci/idm/user/exception/InvalidPasswordUserException.kt
okta/pom.xml
okta/src/main/java/org/ccci/idm/user/okta/dao/OktaUserDao.kt
okta/src/main/java/org/ccci/idm/user/okta/dao/exception/OktaDaoException.kt
okta/src/test/.gitignore
okta/src/test/java/org/ccci/idm/user/okta/dao/OktaUserDaoUpdateUserIT.kt
okta/src/test/java/org/ccci/idm/user/okta/dao/OktaUserDaoUpdateUserTest.kt
okta/src/test/resources/config.xml
pom.xml

In order to run the integration test you need to create `okta/src/test/resources/okta.properties` with these properties:
```
okta.orgUrl=https://cru.oktapreview.com/
okta.apiKey={apiKey}
```
The Unit Test emulates the error response that the server actually returns

Okta invalid password exception
